name: mini2Dx
markdown: redcarpet
pygments: true

navigation:
- text: Home
  url: /
- text: Blog
  url: /blog/
- text: Documentation
  url: /documentation/
- text: Tutorials
  url: /tutorials/
- text: Community
  url: http://reddit.com/r/mini2Dx
- text: Source
  url: https://github.com/tomcashman/mini2Dx
- text: Downloads
  url: /downloads/